title: Cem Kaya
description: Solutions Architect | IMS & 5G Core Network
url: "https://kayacem.com"
baseurl: ""

author:
  name: Cem Kaya
  title: Solution Architect & Data Scientist
  email: cem8kaya@gmail.com
  linkedin: cemkaya
  github: cem8kaya
  location: Istanbul, Turkey

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
